// Extracts the ABIs the frontend needs from the Foundry build output.
// Usage: node scripts/generate-abis.mjs   (run from the repository root)
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
// contract name in out/ → exported identifier in abis.ts
const contracts = {
  ISAFactory: 'isaFactoryAbi',
  ISAAgreement: 'isaAgreementAbi',
  TestUSD: 'testUSDAbi',
  DemoIncomeVerifier: 'demoIncomeVerifierAbi',
}

const parts = [
  '// AUTO-GENERATED by scripts/generate-abis.mjs — do not edit by hand.',
  '// Regenerate with: cd contracts && forge build && cd .. && node scripts/generate-abis.mjs',
  '',
]

for (const [name, exportName] of Object.entries(contracts)) {
  const artifact = join(root, 'contracts', 'out', `${name}.sol`, `${name}.json`)
  if (!existsSync(artifact)) {
    console.error(`Missing artifact for ${name}. Run "forge build" in contracts/ first.`)
    process.exit(1)
  }
  const { abi } = JSON.parse(readFileSync(artifact, 'utf8'))
  parts.push(`export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const`)
  parts.push('')
}

const out = join(root, 'web', 'src', 'lib', 'abis.ts')
writeFileSync(out, parts.join('\n'))
console.log(`Wrote ${out} (${Object.keys(contracts).join(', ')})`)
